name: sywari
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <=3.5.0"
  flutter: ">=3.13.2 <=3.19.1"
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^1.1.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  flutter_locales: ^3.0.2
  google_fonts: ^6.2.1
  url_launcher: ^6.0.20
  flutter_svg: ^2.0.5
  xml: ^6.1.0
  logger: ^1.0.0
  windows1251: ^2.0.0
  file_picker: ^5.2.0
  go_router: ^6.0.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icon/sywari.png"
  image_path: "assets/icon/sywari.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/sywari.png
    - assets/icons/
    - assets/Расписание.json